name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: sh build.sh

    - name: Install a package
      run: ./ferment install bitgit
    - name: List Packages
      run: ./ferment list
    - name: Show Current Barrells
      run: ./ferment search
    - name: Show Version
      run: ./ferment -v
