name: Build Release

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Install pre-requisites
      run: brew install jq
    - name: Build
      run: sh build.sh
    - name: Get Version
      id: get_version
      run: echo ::set-output name=VERSION::$(jq -r '.version' ferment.config.json)
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ steps.get_version.outputs.VERSION }}"
        prerelease: true
        title: "Release v${{ steps.get_version.outputs.VERSION }}"
        files: |
          bin/ferment
